# generated by datamodel-codegen:
#   filename:  complation_database.schema.json
#   timestamp: 2025-05-27T14:12:59+00:00
# ref: hhttps://clang.llvm.org/docs/JSONCompilationDatabase.html
# schema manually created
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Directory(RootModel[str]):
    root: str


class File(RootModel[str]):
    root: str


class Arguments(RootModel[List[str]]):
    root: List[str]


class Output(RootModel[str]):
    root: str


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    directory: Directory
    file: File
    arguments: Arguments
    output: Optional[Output] = None
